#!/bin/sh

# Required environment variables:
#
# DATABASE
#   Path to a sqlite3 database containing the measurement data.
#
# FIRST
#   ISO 8601 date of the first day of data to fetch.
#
# LAST
#   ISO 8601 date of the last day of data to fetch.

/usr/local/bin/sqlite3 "$DATABASE" <<END_SQL
.headers off
.mode tabs
.output dump.txt
select when_iso, co2_ppm
from co2_raw
where when_iso between '$FIRST' and '$LAST' or instr(when_iso, '$LAST') = 1
order by when_iso;
END_SQL

# If there are many more than 1000 points, skip some points so there are about
# 1000 remaining.
# multiple=$(printf '%s / %s\n' "$(wc -l <dump.txt)" 5000 | bc)
# if [ "$multiple" -gt 1 ]; then
#   >dump.txt.tmp awk "(NR - 1) % $multiple == 0" dump.txt
#   mv dump.txt.tmp dump.txt
# fi

printf 'image/svg+xml' >response/headers/Content-Type

>response/body gnuplot <<'END_GNUPLOT'
set xdata time
set timefmt '%Y-%m-%dT%H:%M:%SZ'

set xlabel 'Time (UTC)' offset 0,-1
set ylabel 'CO₂ Concentration (ppm)'

set title 'CO₂ Concentration versus Time'

# Give the legend a solid background, and make sure that the border of the
# graph isn't drawn over it.
set key center top box opaque
set border back

set terminal svg size 1024,768 fixed enhanced font 'Arial,12' butt dashlength 1.0 background rgb 'antiquewhite'

set tics front

plot 'dump.txt' using 1:2 title 'CO₂ Concentration (ppm)'
END_GNUPLOT

# Edit the resulting SVG's <title> in place.
xmlstarlet edit --inplace --update "//_:svg/_:title" --value 'CO₂ Concentration' response/body


