#!/bin/sh

# Required environment variables:
#
# DATABASE
#   Path to a sqlite3 database containing the measurement data.
#
# FIRST
#   ISO 8601 date of the first day of data to fetch.
#
# LAST
#   ISO 8601 date of the last day of data to fetch.

/usr/local/bin/sqlite3 "$DATABASE" <<END_SQL
.headers off
.mode tabs
.output dump.txt

select
  co2_ppm / 100 * 100 as ppm_bin,
  count(*) as freq
from co2_raw
group by co2_ppm / 100 order by ppm_bin;
END_SQL

printf 'image/svg+xml' >response/headers/Content-Type

>response/body gnuplot <<'END_GNUPLOT'
set xlabel 'CO₂ Concentration (ppm)'
set ylabel 'Frequency'

set boxwidth 0.9 relative
set style fill solid 1.0

set title 'CO₂ Concentration Histogram'

set terminal svg size 1024,768 fixed enhanced font 'Arial,12' butt dashlength 1.0 background rgb 'antiquewhite'

set tics front

plot 'dump.txt' using 1:2 notitle with boxes
END_GNUPLOT

# Edit the resulting SVG's <title> in place.
xmlstarlet edit --inplace --update "//_:svg/_:title" --value 'CO₂ Concentration Histogram' response/body

