#!/bin/sh

# Required environment variables:
#
# DATABASE
#   Path to a sqlite3 database containing the measurement data.
#
# FIRST
#   ISO 8601 date of the first day of data to fetch.
#
# LAST
#   ISO 8601 date of the last day of data to fetch.

/usr/local/bin/sqlite3 "$DATABASE" <<END_SQL
.headers off
.mode columns
.output dump.txt

select tens * 10 as milliseconds, frequency
from (
  select duration_nanoseconds / (1000*1000*10) as tens,
  sum(dupe_count + 1) as frequency
  from co2_request_duration
    inner join co2_raw on co2_request_duration.co2_raw_id = co2_raw.id
  where date(co2_raw.when_iso) between '$FIRST' and '$LAST'
  group by tens
  order by tens
  )
order by milliseconds;
END_SQL

printf 'image/svg+xml' >response/headers/Content-Type

>response/body gnuplot <<'END_GNUPLOT'
set xlabel 'CO₂ Sensor Request Latency (ms)'
set ylabel 'Frequency'

set boxwidth 0.9 relative
set style fill solid 1.0

set title 'CO₂ Sensor Request Latency Histogram'

set terminal svg size 1024,769 fixed enhanced font 'Arial,12' butt dashlength 1.0

set logscale x
set logscale y

plot 'dump.txt' using 1:2 notitle with boxes
END_GNUPLOT

