#!/bin/sh

# Required environment variables:
#
# DATABASE
#   Path to a sqlite3 database containing the measurement data.
#
# FIRST
#   ISO 8601 date of the first day of data to fetch.
#
# LAST
#   ISO 8601 date of the last day of data to fetch.

/usr/local/bin/sqlite3 "$DATABASE" <<END_SQL
.headers off
.mode tabs
.timeout 1000 -- milliseconds
.output dump.txt
select temperature_celsius, sum(dupe_count + 1)
from reading
where when_iso between '$FIRST' and '$LAST' or instr(when_iso, '$LAST') = 1
group by temperature_celsius
order by temperature_celsius;
END_SQL

printf 'image/svg+xml' >response/headers/Content-Type

>response/body gnuplot <<'END_GNUPLOT'
set xlabel 'Temperature (°C)'
set ylabel 'Frequency'

set boxwidth 0.9 relative
set style fill solid 1.0

set title 'Temperature Histogram'

set terminal svg size 1024,768 fixed enhanced font 'Arial,12' butt dashlength 1.0 background rgb 'antiquewhite'

set tics front

plot 'dump.txt' using 1:2 notitle with boxes
END_GNUPLOT

# Edit the resulting SVG's <title> in place.
xmlstarlet edit --inplace --update "//_:svg/_:title" --value 'Temperature Histogram' response/body

