#!/bin/sh

# Required environment variables:
#
# DATABASE
#   Path to a sqlite3 database containing the measurement data.
#
# FIRST
#   ISO 8601 date of the first day of data to fetch.
#
# LAST
#   ISO 8601 date of the last day of data to fetch.

/usr/local/bin/sqlite3 "$DATABASE" <<END_SQL
.headers off
.mode tabs
.timeout 1000 -- milliseconds
.output dump.txt
select when_iso, duration_nanoseconds / 1000000 as duration_milliseconds
from wine_cooler_request
where when_iso between '$FIRST' and '$LAST' or instr(when_iso, '$LAST') = 1
order by when_iso;
END_SQL

printf 'image/svg+xml' >response/headers/Content-Type

>response/body gnuplot <<'END_GNUPLOT'
set xdata time
set timefmt '%Y-%m-%dT%H:%M:%SZ'

set xlabel 'Time (UTC)' offset 0,-1
set ylabel 'Wine Cooler Request Latency (ms)'

set title 'Wine Cooler Request Latency versus Time'

# Give the legend a solid background, and make sure that the border of the
# graph isn't drawn over it.
set key center top box opaque
set border back

set terminal svg size 1024,768 fixed enhanced font 'Arial,12' butt dashlength 1.0 background rgb 'antiquewhite'

set tics front

set logscale y

plot 'dump.txt' using 1:2 title 'Wine Cooler Request Duration (ms)'
END_GNUPLOT

# Edit the resulting SVG's <title> in place.
xmlstarlet edit --inplace --update "//_:svg/_:title" --value 'Wine Cooler Request Latency' response/body


